version: 2.1
orbs:
  react: thefrontside/react@0.2.0
workflows:
  push:
    jobs:
      - react/install
      - react/test:
          requires:
            - react/install
      - linting:
          requires:
            - react/install

jobs:
  linting:
    docker:
      - image: circleci/command-convenience:0.1
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run: yarn eslint src/**/*.ts{,x} --max-warnings=0 --format junit
