version: 2.1
orbs:
  react: thefrontside/react@0.2.0
  eslint: arrai/eslint@2.0.2
workflows:
  push:
    jobs:
      - react/install
      - react/test:
          requires:
            - react/install
